services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      # Mount code for hot-reloading during development
      - .:/app
      # Use Docker's volume for node_modules to avoid overwriting with host's node_modules
      - /app/node_modules
      # Create a named volume for Next.js cache to improve rebuild performance
      - next-cache:/app/.next/cache
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=9000
      # Add any additional environment variables here
    restart: unless-stopped
    # Setting healthcheck to ensure the container is running properly
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Set memory limits to prevent container from using too much memory
    deploy:
      resources:
        limits:
          memory: 2G

# Define named volumes for persisting data across container restarts
volumes:
  next-cache:
    # Next.js cache volume
